### PR TITLE
feat: add ionic framework support

### PR DESCRIPTION
**Pull request by Svenskunganka**
Ionic finally added official support for Meteor (see [#3133](https://github.com/driftyco/ionic/pull/3133)) so decided to add support for it to this generator.

One thing I didn't implement was pagination, search & sort support due to the directive not being fully compatible with Ionic CSS - anyhow, the basics is there.

### CODE REVIEW

**Comment by ndxbxrme** [comment]
Hey Tom
Thanks for your contributions!
I'm getting a few errors when building from your Ionic generator...
image

and when trying to add a new thing to the list
image
which seems to be caused by one of the ionic elements creating it's own child scope
image

fixes it, but seems a bit hacky

**Comment by ndxbxrme** [comment]
Using Coffescript, Jade and Stylus

**Comment by Svenskunganka** [comment]
Hey! Yeah I noticed that now, seemed to be working until the last thing I did was swap out `<div ui-view=""></div>` with `<ion-content ui-view=""></ion-content>` so there seem to be some clash between `ui-view` directive and `ion-content` directive. Sloppy of me that I didn't notice it right away.

The issue is that if I do `<div ui-view=""></div>` the `ion-content` directive inside the view doesn't become scrollable.

I'll commit a fix as soon as I find a workaround

**Comment by Svenskunganka** [comment]
Alright, I've tested as much as I can and I've tackled the error.

The `ion-content` directive is notorious as f**k, it creates a child scope so any binding in the view has to be referenced by `$parent`, e.g `$parent.things, $parent.form`.

Also removed ui-router dep when selecting ionic since ionic already have that as dependency with nice transitions and whatnot.

**Comment by ndxbxrme** [comment]
Cool, I'll give it a test when I finish work

**Comment by Svenskunganka** [comment]
Awesome!

I've actually never worked with CoffeeScript or a Yeoman Generator before so there may be some weird Coffee syntax somewhere. This was fun! :smile:

**Comment by Svenskunganka** [comment]
The latest release `angular@1.0.0-rc.10` replaced `meteor-include` directive with `blaze-template` directive (see [#707](https://github.com/Urigo/angular-meteor/issues/707)). `urigo:angular-blaze-template` dependency had to be added. Applied those changes in this pull as well.

**Comment by ndxbxrme** [comment]
Hey Tom
Looks good.  Could you make ionic templates for /generator/route too?

**Comment by Svenskunganka** [comment]
There, completely forgot about the route generator, everything should be in place now for this pull.

**Comment by ndxbxrme** [comment]
Awesome, I've added it to the generator (v0.18.0)
I did a little tidying up, let me know if I've done anything stupid:)
Thanks for your hard work!

**Comment by Svenskunganka** [comment]
Awesome! I can see now that I missed quite a lot, thanks for covering for me! Overall love this generator, you've done a very nice job!

**Comment by Urigo** [comment]
Wow guys, that's awesome!

**Comment by ndxbxrme** [comment]
Thanks Uri, we're honoured:)

**Pull request merged**
